version: "3.9"
services:
    api:
        build: ./api
        ports:
            - "8000:80"
        depends_on:
            - db
        environment:
            DB_SERVER: "db"
            DB_USER: "sa"
            DB_USER_PASSWORD: "Your_password123"
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"